// Generated by CoffeeScript 2.5.1
import {
  Controller
} from "stimulus";

export default (function() {
  var _Class;

  _Class = class extends Controller {
    initialize() {
      return console.log("Finder initializing");
    }

    connect() {
      return console.log("Finder connecting");
    }

    find(event) {
      var data, status, xhr;
      console.log("finding...");
      [data, status, xhr] = event.detail;
      this.foundPostTarget.innerHTML = xhr.response;
      return this.titleTarget.value = "";
    }

  };

  _Class.targets = ["title", "foundPost"];

  return _Class;

}).call(this);
