// Generated by CoffeeScript 2.5.1
var application, context;

import {
  Application
} from "stimulus";

import {
  definitionsFromContext
} from "stimulus/webpack-helpers";

application = Application.start();

context = require.context("controllers", true, /_controller\.js$/);

application.load(definitionsFromContext(context));
